version: '2.1'
services:
  nodejs:
  #  command: npm start
    image: reg-gitlab.btcbit.loc:3343/romancevicsp/ws-proxy:0.0.2
    networks:
      - dev_microservices
    container_name: nodejs
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "80:8080"
      - "81:8081"
    environment:
      - RABBITMQ_SSL=false
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmqSomePass1122
      - RABBITMQ_HOST=amqp://rabbitmq
    volumes:
      - ./app:/usr/src/app
    logging:
      options:
        max-size: "1MB"
        max-file: "3"

  rabbitmq:
    image: reg-gitlab.btcbit.loc:3343/container/rabbit/alpine:3.7.16
    networks:
      - dev_microservices
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmqSomePass1122
      - RABBITMQ_LOGS=/var/lib/rabbitmq/logs
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_USERNAME=rabbitmq
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      options:
        max-size: "1MB"
        max-file: "3"
networks:
  dev_microservices:
volumes:
  var-www-somevolume: